/**:
  ros__parameters:
    wheel_radius: 0.20 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.04 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.50 # between front wheel center and rear wheel center
    wheel_tread: 0.60 # between left wheel center and right wheel center
    front_overhang: 0.20 # between front wheel center and vehicle front
    rear_overhang: 0.30 # between rear wheel center and vehicle rear
    left_overhang: 0.0 # between left wheel center and vehicle left
    right_overhang: 0.0 # between right wheel center and vehicle right    
    vehicle_height: 0.75
    max_steer_angle: 0.70 # [rad]
